# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('Sensors', src, depend = ['RT_USING_I2C', 'RT_USING_SENSOR'], CPPPATH = CPPPATH)

Return('group')
